spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:userdb
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    serialization:
      WRITE_DURATIONS_AS_TIMESTAMPS: false
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    com:
      fasterxml:
        jackson: DEBUG
      springframework:
        web: DEBUG